# repository secrets:
# -------------------
# - deploy_to_host
# - drone_deployer_ssh_key_private
# - drone_deployer_ssh_username
# - repository_api  = registry.domain.tld/lorem-list/lorem-list-api
# - repository_client_web = registry.domain.tld/lorem-list/lorem-list-client-web

# organization secrets:
# -------------------
# - nyx_flyingfishflash_token_codeberg
# - nyx_flyingfishflash_token_github
# - nyx_flyingfishflash_token_gitlab
# - nyx_flyingfishflash_token_lan
# - registry_hostname
# - registry_password
# - registry_username
# - sonar_host
# - sonar_token

#kind: pipeline
#type: docker
#name: "web client - build"
#
#volumes:
#  - name: drone_cache
#    host:
#      path: /var/lib/docker/volumes_managed/drone_cache
#
#trigger:
#  event:
#    - push
#    - tag
#  ref:
#    - refs/heads/build-*
#    - refs/heads/feature-*
#    - refs/heads/fix-*
#    - refs/heads/main
#    - refs/heads/perf-*
#    - refs/heads/refactor-*
#    - refs/heads/style-*
#    - refs/heads/release
#
#environment:
#  VERSION: .version
#  BUILD: .build
#
#steps:
#  - name: infer version
#    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
#    commands:
#      # nyx requires git tags to infer the current version
#      - git fetch --tags -q
#      - rm -fv $VERSION
#      - echo "export NYX_CURRENT_VERSION=$(nyx infer --fatal | grep 'current version' | awk '{ print $NF }' | tr -d '\n')" > $VERSION
#      - cat $VERSION
#
#  - name: build
#    image: node:18-alpine
#    depends_on:
#      - infer version
#    commands:
#      - source $VERSION
#      - |
#        cat <<EOT >> $BUILD
#        export BUILD_SCM_COMMIT_SHORT_SHA=$(echo $DRONE_COMMIT_SHA | cut -c1-8)
#        export BUILD_CLIENT_NPM_CACHE=/drone/drone_cache/$DRONE_REPO/client/npm
#        export BUILD_CLIENT_DIST=/drone/drone_cache/$DRONE_REPO/client/dist
#        export PATH=/drone/src/frontend/node_modules/.bin:$PATH
#        EOT
#      - source $BUILD
#      - env | awk -v s="BUILD_" 'index($0, s) == 1' | LC_ALL=C sort
#      - mkdir -pv $BUILD_CLIENT_NPM_CACHE
#      - mkdir -pv $BUILD_CLIENT_DIST
#      - cd /drone/src/frontend
#      - |
#        export JSON_BUILD_PROPERTIES=$(node -pe "
#          JSON.stringify({
#            artifact: new String('ledger'),
#            ciPipelineId: process.env.DRONE_BUILD_NUMBER,
#            ciPlatform: new String('drone'),
#            commit: process.env.BUILD_SCM_COMMIT_SHORT_SHA,
#            group: Symbol(''),
#            name: Symbol(''),
#            time: Symbol(''),
#            version: process.env.NYX_CURRENT_VERSION
#          });
#        ")
#      - echo $JSON_BUILD_PROPERTIES > src/assets/buildProperties.json
#      - cat src/assets/buildProperties.json
#      - npm version $NYX_CURRENT_VERSION --no-git-tag-version
#      - npm ci --cache $BUILD_CLIENT_NPM_CACHE --prefer-offline
#      - ng version
#      - ng build --configuration production --output-path=$BUILD_CLIENT_DIST/ledger-frontend
#      - printf "\n$(ls -1a $BUILD_CLIENT_DIST/ledger-frontend | wc -l) files in $BUILD_CLIENT_DIST/ledger-frontend\n"
#    volumes:
#      - name: drone_cache
#        path: /drone/drone_cache

#---
kind: pipeline
type: docker
name: "api - build"

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/build-*
    - refs/heads/feature-*
    - refs/heads/fix-*
    - refs/heads/main
    - refs/heads/perf-*
    - refs/heads/refactor-*
    - refs/heads/release
    - refs/heads/style-*

volumes:
  - name: drone_cache
    host:
      path: /var/lib/docker/volumes_managed/drone_cache

services:
  - name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: lorem-list
      POSTGRES_PASSWORD: lorem-list
      POSTGRES_DB: lorem-list

steps:
  # nyx requires git tags to infer the current version
  - name: fetch git tags
    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
    commands:
      - git fetch --tags -q

  - name: verify postgres
    image: postgres
    commands:
      - |
        until psql "dbname=lorem-list host=postgres user=lorem-list password=lorem-list port=5432" \
          -c "select 1;" >/dev/null 2>&1; do sleep 1; done
      - |
        psql "dbname=lorem-list host=postgres user=lorem-list password=lorem-list port=5432" \
          -c "select count(*) from pg_catalog.pg_tables;"

  - name: build
    image: gradle:8-jdk17
    depends_on:
      - fetch git tags
      - verify postgres
    commands:
      - export GRADLE_USER_HOME=/drone/drone_cache/$DRONE_REPO/api/gradle-user-home
      - echo $GRADLE_USER_HOME
      - mkdir -pv $GRADLE_USER_HOME
      - touch $GRADLE_USER_HOME/gradle.properties
      - echo org.gradle.caching=true > $GRADLE_USER_HOME/gradle.properties
      - echo org.gradle.daemon=false >> $GRADLE_USER_HOME/gradle.properties
      - export GRADLE_PROJECT_BUILD_DIR=/drone/drone_cache/$DRONE_REPO/api/build
      - echo $GRADLE_PROJECT_BUILD_DIR
      - mkdir -pv $GRADLE_PROJECT_BUILD_DIR
#      - >
#        gradle
#        :api:explodebootjar
#        :api:copyBuildInfo
#        :api:testClasses
#        :api:spotlessCheck
#        :api:test
#        :api:integrationTests
#        :api:bootBuildInfo
#        -PbuildDir=$GRADLE_PROJECT_BUILD_DIR
      - >
        gradle
        :api:testClasses
        :api:spotlessCheck
        :api:test
        :api:bootBuildInfo
        -PbuildDir=$GRADLE_PROJECT_BUILD_DIR
#      - >
#        gradle
#        :api:integrationTests
#        -Dspring.profiles.active=postgresql
#        -Dspring.datasource.url=jdbc:postgresql://postgres:5432/lorem-list
#        -Dspring.datasource.username=lorem-list
#        -Dspring.datasource.password=lorem-list
#        -Dspring.datasource.platform=postgresql
#        -PbuildDir=$GRADLE_PROJECT_BUILD_DIR
      - >
        /drone/src/scripts/ci/drone/drone-is-sonar-configured.sh &&
        gradle
        sonar
        -Dsonar.host.url=$SONAR_HOST
        -Dsonar.token=$SONAR_TOKEN
        -Dsonar.qualitygate.wait=true
        -PbuildDir=$GRADLE_PROJECT_BUILD_DIR
    environment:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    volumes:
      - name: drone_cache
        path: /drone/drone_cache

#---
#kind: pipeline
#name: "publish - image"
#type: docker
#
#trigger:
#  event:
#    - push
#  ref:
#    - refs/heads/feature-*
#    - refs/heads/fix-*
#    - refs/heads/perf-*
#    - refs/heads/refactor-*
#    - refs/heads/release
#
#depends_on:
#  - "web client - build"
#  - "api - build"
#
#volumes:
#  - name: drone_cache_client_dist
#    host:
#      path: /var/lib/docker/volumes_managed/drone_cache/flyingfishflash/lorem-list/client/dist
#  - name: drone_cache_api_build
#    host:
#      path: /var/lib/docker/volumes_managed/drone_cache/flyingfishflash/lorem-list/api/build
#
#environment:
#  TAGS: .tags
#  VERSION: .version
#
#steps:
#  - name: generate image tags
#    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
#    commands:
#      # nyx requires git tags to infer the current version
#      - git fetch --tags -q
#      - nyx infer --fatal | grep 'current version' | awk '{ print $NF }' | tr -d '\n' > $TAGS
#      - cat $TAGS && echo
#
#  - name: publish client-web
#    image: plugins/docker
#    depends_on:
#      - generate image tags
#    privileged: true
#    settings:
#      auto_tag: false
#      context: /drone/src/client-web/
#      dockerfile: /drone/src/client-web/Dockerfile
#      repo:
#        from_secret: repository_client_web
#      registry:
#        from_secret: registry_hostname
#      username:
#        from_secret: registry_username
#      password:
#        from_secret: registry_password
#    volumes:
#      - name: drone_cache_client_dist
#        path: /drone/src/client-web/dist
#
#  - name: publish api
#    image: plugins/docker
#    depends_on:
#      - generate image tags
#    privileged: true
#    settings:
#      auto_tag: false
#      context: /drone/src/api/
#      dockerfile: /drone/src/api/Dockerfile
#      repo:
#        from_secret: repository_api
#      registry:
#        from_secret: registry_hostname
#      username:
#        from_secret: registry_username
#      password:
#        from_secret: registry_password
#    volumes:
#      - name: drone_cache_api_build
#        path: /drone/src/api/build
#
#---
#kind: pipeline
#name: "publish - release"
#type: docker
#
#trigger:
#  event:
#    - push
#  ref:
#    - refs/heads/release
#
#depends_on:
#  - "publish - image"
#
#volumes:
#  - name: drone_cache
#    host:
#      path: /var/lib/docker/volumes_managed/drone_cache
#
#steps:
#  - name: "publish - release"
#    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
#    environment:
#      NYX_FLYINGFISHFLASH_TOKEN_CODEBERG:
#        from_secret: nyx_flyingfishflash_token_codeberg
#      NYX_FLYINGFISHFLASH_TOKEN_GITHUB:
#        from_secret: nyx_flyingfishflash_token_github
#      #      NYX_FLYINGFISHFLASH_TOKEN_GITLAB:
#      #        from_secret: nyx_flyingfishflash_token_gitlab
#      NYX_FLYINGFISHFLASH_TOKEN_LAN:
#        from_secret: nyx_flyingfishflash_token_lan
#    commands:
#      # nyx requires git tags to infer the current version
#      - git fetch --tags -q
#      # nyx is configured to push to the codeberg remote
#      # the codeberg remote propagates itself to GitHub and gitlab
#      - git remote add codeberg https://codeberg.org/flyingfishflash/lorem-list.git
#      - mkdir /drone/src/build
#      - nyx publish --dry-run=false
#    volumes:
#      - name: drone_cache
#        path: /drone/cache

#---
#kind: pipeline
#name: "deploy - development"
#type: docker
#
#trigger:
#  event:
#    - push
#  ref:
#    - refs/heads/feature-*
#    - refs/heads/fix-*
#    - refs/heads/perf-*
#    - refs/heads/refactor-*
#
#depends_on:
#  - "publish - image"
#
#environment:
#  VERSION: .version
#
#steps:
#  - name: infer version
#    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
#    commands:
#      # nyx requires git tags to infer the current version
#      - git fetch --tags -q
#      - rm -fv $VERSION
#      - echo "export NYX_CURRENT_VERSION=$(nyx infer --fatal | grep 'current version' | awk '{ print $NF }' | tr -d '\n')" > $VERSION
#      - cat $VERSION
#
#  - name: create inventory file
#    image: alpine:latest
#    environment:
#      DEPLOY_TO_HOST:
#        from_secret: deploy_to_host
#    commands:
#      - echo "$DEPLOY_TO_HOST" > scripts/ci/drone/deploy/inventory
#
#  - name: create variables file
#    image: alpine
#    depends_on:
#      - infer version
#    environment:
#      REGISTRY_URL:
#        from_secret: REGISTRY_HOSTNAME
#    commands:
#      - source $VERSION
#      - ls -la
#      - echo "---" > scripts/ci/drone/deploy/variables.yaml
#      - 'echo "tag: $NYX_CURRENT_VERSION" >> scripts/ci/drone/deploy/variables.yaml'
#      - 'echo "registry_url: $REGISTRY_URL/lorem-list" >> scripts/ci/drone/deploy/variables.yaml'
#      - cat scripts/ci/drone/deploy/variables.yaml
#
#  # the secret containing the ssh private key must be created via the CLI
#  # drone secret add --repository flyingfishflash/lorem-list --name secret_name --data @/home/xxx/.ssh/id_xxx
#  - name: execute playbook
#    image: plugins/ansible
#    depends_on:
#      - create inventory file
#      - create variables file
#    settings:
#      extra_vars: 'region=dev'
#      galaxy: scripts/ci/drone/deploy/requirements.yaml
#      inventory: scripts/ci/drone/deploy/inventory
#      playbook: scripts/ci/drone/deploy/deploy.yaml
#      private_key:
#        from_secret: drone_deployer_ssh_key_private
#      user: drone_deployer_ssh_username
#
#---
#kind: pipeline
#name: "deploy - production"
#type: docker
#
#trigger:
#  event:
#    - push
#    - tag
#  ref:
#    - refs/tags/*
#
#depends_on:
#  - "publish - image"
#
#environment:
#  VERSION: .version
#
#steps:
#  - name: infer version
#    image: registry.flyingfishflash.net/flyingfishflash/nyx:latest
#    commands:
#      # nyx requires git tags to infer the current version
#      - git fetch --tags -q
#      - rm -fv $VERSION
#      - echo "export NYX_CURRENT_VERSION=$(nyx infer --fatal | grep 'current version' | awk '{ print $NF }' | tr -d '\n')" > $VERSION
#      - cat $VERSION
#
#  - name: create inventory file
#    image: alpine:latest
#    environment:
#      DEPLOY_TO_HOST:
#        from_secret: deploy_to_host
#    commands:
#      - echo "$DEPLOY_TO_HOST" > scripts/ci/drone/deploy/inventory
#
#  - name: create variables file
#    image: alpine
#    depends_on:
#      - infer version
#    environment:
#      REGISTRY_URL:
#        from_secret: REGISTRY_HOSTNAME
#    commands:
#      - source $VERSION
#      - ls -la
#      - echo "---" > scripts/ci/drone/deploy/variables.yaml
#      - 'echo "tag: $NYX_CURRENT_VERSION" >> scripts/ci/drone/deploy/variables.yaml'
#      - 'echo "registry_url: $REGISTRY_URL/lorem-list" >> scripts/ci/drone/deploy/variables.yaml'
#      - cat scripts/ci/drone/deploy/variables.yaml
#
#  # the secret containing the ssh private key must be created via the CLI
#  # drone secret add --repository flyingfishflash/lorem-list --name secret_name --data @/home/xxx/.ssh/id_xxx
#  - name: execute playbook
#    image: plugins/ansible
#    depends_on:
#      - create inventory file
#      - create variables file
#    settings:
#      extra_vars: 'region=prd'
#      galaxy: scripts/ci/drone/deploy/requirements.yaml
#      inventory: scripts/ci/drone/deploy/inventory
#      playbook: scripts/ci/drone/deploy/deploy.yaml
#      private_key:
#        from_secret: drone_deployer_ssh_key_private
#      user: drone_deployer_ssh_username
