---

config:
  application:
#    name: &application-name "lorem-list"
#    description: &application-description "A Kotlin/Spring Boot based list manager"
    documentation: 'https://lorem-list.wiki.github.org/docs'
    api-v1-url-path: /api/v1

debug: 'false'

logging:
  level:
    org:
      flywaydb: warn
      springframework:
        security: DEBUG

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      cors:
        allowed-origins: '*'
        allowed-methods: 'OPTIONS, GET'
      exposure:
        include: 'info,health'

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: 'false'
  port: '8282'
  servlet:
    context-path: /api/v1
#    session:
#      cookie:
#        secure: "true"
#        http-only: "true"
#      timeout: "5m"
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

spring:
  exposed:
    show-sql: 'true'
    generate-ddl: 'false'
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: 'false'
  main:
    banner-mode: 'off'
  mvc:
    throw-exception-if-no-handler-found: 'true'
    problemdetails:
      enabled: true
  output:
    ansi:
      enabled: always
  profiles:
    active: h2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://zitadel.flyingfishflash.net'
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  sql:
    init:
      mode: never
trace: 'false'

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    defaultModelsExpandDepth: 3
    operationsSorter: alpha
    tagsSorter: alpha
